# Generated by Django 5.1.2 on 2026-04-23 01:42

import flyer_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flyer_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        default="RCCG City of Refuge Birthday Flyer Generator",
                        max_length=150,
                    ),
                ),
                (
                    "navbar_title",
                    models.CharField(
                        default="RCCG City of Refuge Birthday Flyer Generator",
                        max_length=150,
                    ),
                ),
                (
                    "footer_owner",
                    models.CharField(
                        default="RCCG City of Refuge Media Unit", max_length=150
                    ),
                ),
                (
                    "footer_rights_text",
                    models.CharField(default="All rights reserved.", max_length=120),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to=flyer_app.models.branding_logo_path
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site branding",
                "verbose_name_plural": "Site branding",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
        migrations.AlterField(
            model_name="birthdayflyer",
            name="generated_flyer",
            field=models.ImageField(
                blank=True, upload_to=flyer_app.models.generated_flyer_path
            ),
        ),
        migrations.AlterField(
            model_name="birthdayflyer",
            name="uploaded_photo",
            field=models.ImageField(upload_to=flyer_app.models.upload_photo_path),
        ),
    ]
